[project]
name = "barcade"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nis Meinert", email = "mail@nismeinert.de" }
]
requires-python = ">=3.13"
dependencies = [
    "wasmtime>=38.0.0",
]

[build-system]
requires = ["uv_build>=0.9.4,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "ruff>=0.14.1",
]

[project.scripts]
clicli = "barcade.clicli:main"

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "I"]
ignore = ["E741"]
